// <auto-generated />
namespace HTML5.ScratchPad.DDD.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Customerandproducttoonetomanyoptional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Customerandproducttoonetomanyoptional));
        
        string IMigrationMetadata.Id
        {
            get { return "201511281254590_Customer and product to one to many optional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
