// <auto-generated />
namespace HTML5.ScratchPad.DDD.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cascadedeleteaddresses2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cascadedeleteaddresses2));
        
        string IMigrationMetadata.Id
        {
            get { return "201512041313369_cascade delete addresses2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
